const memeImages = [
    {
        img: '1',
        width: 342,
        height: 400,
        class: 'mouse',
    },
    {
        img: '2',
        width: 736,
        height: 741,
        class: 'dog',
    },
    {
        img: '3',
        width: 640,
        height: 640,
        class: 'mouse',
    },
    {
        img: '4',
        width: 660,
        height: 495,
        class: 'cat',
    },
    {
        img: '5',
        width: 736,
        height: 850,
        class: 'cat',
    },
    {
        img: '6',
        width: 449,
        height: 449,
        class: 'dog',
    },
    {
        img: '7',
        width: 736,
        height: 736,
        class: 'monkey',
    },
    {
        img: '8',
        width: 606,
        height: 499,
        class: 'monkey',
    },
    {
        img: '9',
        width: 552,
        height: 552,
        class: 'monkey',
    },
    {
        img: '10',
        width: 735,
        height: 715,
        class: 'cat',
    },
    {
        img: '11',
        width: 606,
        height: 607,
        class: 'dog',
    },
    {
        img: '12',
        width: 640,
        height: 641,
        class: 'cat',
    },
    {
        img: '13',
        width: 735,
        height: 700,
        class: 'dog',
    },
    {
        img: '14',
        width: 736,
        height: 728,
        class: 'dog',
    },
    {
        img: '15',
        width: 735,
        height: 1081,
        class: 'cat',
    },
    {
        img: '16',
        width: 736,
        height: 736,
        class: 'dog',
    },
    {
        img: '17',
        width: 675,
        height: 1200,
        class: 'etc',
    },
    {
        img: '18',
        width: 500,
        height: 476,
        class: 'dog',
    },
    {
        img: '19',
        width: 735,
        height: 726,
        class: 'cat',
    },
    {
        img: '20',
        width: 736,
        height: 982,
        class: 'cat',
    },
    {
        img: '21',
        width: 736,
        height: 736,
        class: 'dog',
    },
    {
        img: '22',
        width: 700,
        height: 700,
        class: 'dog',
    },
    {
        img: '23',
        width: 736,
        height: 840,
        class: 'dog',
    },
    {
        img: '24',
        width: 375,
        height: 500,
        class: 'etc',
    },
    {
        img: '25',
        width: 720,
        height: 593,
        class: 'dog',
    },
    {
        img: '26',
        width: 601,
        height: 937,
        class: 'etc',
    },
    {
        img: '27',
        width: 550,
        height: 528,
        class: 'dog',
    },
];

export default memeImages;